### ISSUE TITLE
Getting Started guide, issues building boilerplate

### ISSUE THREAD

**Issue by blzaugg** [metal/metaljs.com#24]
I'm attempting to follow the Getting Started guide:
http://metaljs.com/docs/

But I'm running into issues building the boilerplate

```
administrator@ubuntu - Wed Jun 08 01:55 PM
~/projects/metaljs/boilerplate/1. Hello World
$ npm run build

> metal-modal@0.0.0 build /home/administrator/projects/metaljs/boilerplate/1. Hello World
> gulp build

(node:16543) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[13:55:56] Using gulpfile ~/projects/metaljs/boilerplate/1. Hello World/gulpfile.js
[13:55:56] Starting 'build'...
[13:55:56] Starting 'clean'...
[13:55:56] Finished 'clean' after 8.38 ms
[13:55:56] Starting 'css'...
[13:55:56] Starting 'soy'...
[13:55:57] Finished 'css' after 89 ms
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/template/soy/SoyToIncrementalDomSrcCompiler : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

[13:55:57] Finished 'soy' after 336 ms
[13:55:57] Starting 'build:js'...
[13:55:57] Starting 'build:globals:js'...
Could not find /home/administrator/projects/metaljs/boilerplate/1. Hello World/src/Modal.soy.js
[13:56:04] Finished 'build:globals:js' after 6.74 s
[13:56:04] Finished 'build:js' after 6.74 s
[13:56:04] Starting 'uglify'...
[13:56:05] Finished 'uglify' after 1.71 s
[13:56:05] Finished 'build' after 8.82 s
```

```
$ node -v
v6.2.1

$ npm -v
3.9.3
```

**Comment by mairatma** [comment]
That's the soy version, right? Unfortunately you need to have java 8 installed for the soy compiler to run, that's what this error is about.

**Comment by mairatma** [comment]
We probably need to make that clearer in the setup steps in metaljs.com/docs... We're specifying the node version but not java, which is essential for soy.

**Comment by mairatma** [comment]
I can also try to catch this error from the compiler and explain the problem in a better way, the default error message is hard to understand. It took me a while to figure out what was going on the first time I got it in a test env.

**Comment by blzaugg** [comment]
Yep, that was it. I was running Java 7. I switched to 8 and it worked fine.

**Comment by mairatma** [comment]
I'll keep this open to handle the improvement of adding this version information to the docs.
